openapi: 3.0.0
info:
  title: Auto Care Management API
  version: 2.0.0
  description: API для управления сетью автомобильных моек и сервисных центров
servers:
  - url: http://localhost:3000/api/v1
    description: Development server

tags:
  - name: Клиенты
    description: Операции с клиентами и их транспортными средствами
  - name: Объекты
    description: Управление мойками и инфраструктурой
  - name: Операции
    description: Управление заказами и бронированиями
  - name: Справочники
    description: Базовая информация и классификаторы

paths:
  # === КЛИЕНТЫ И ТРАНСПОРТ ===
  /клиенты:
    get:
      tags: [Клиенты]
      summary: Получение списка зарегистрированных клиентов
      operationId: getCustomers
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Клиент'
    
    post:
      tags: [Клиенты]
      summary: Регистрация нового клиента
      operationId: createCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/НовыйКлиент'
      responses:
        '201':
          description: Клиент успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Клиент'

  /клиенты/{clientId}:
    parameters:
      - name: clientId
        in: path
        required: true
        schema:
          type: integer
          minimum: 1
    
    get:
      tags: [Клиенты]
      summary: Получение детальной информации о клиенте
      operationId: getCustomerById
      responses:
        '200':
          description: Информация о клиенте
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Клиент'
        '404':
          description: Клиент не найден
    
    put:
      tags: [Клиенты]
      summary: Полное обновление данных клиента
      operationId: updateCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ОбновлениеКлиента'
      responses:
        '200':
          description: Данные клиента обновлены
    
    delete:
      tags: [Клиенты]
      summary: Удаление клиента из системы
      operationId: deleteCustomer
      responses:
        '204':
          description: Клиент удален

  /транспортные-средства:
    get:
      tags: [Клиенты]
      summary: Получение списка всех транспортных средств
      operationId: getAllVehicles
      responses:
        '200':
          description: Список транспортных средств
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ТранспортноеСредство'
    
    post:
      tags: [Клиенты]
      summary: Добавление нового транспортного средства
      operationId: addVehicle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/НовоеТранспортноеСредство'
      responses:
        '201':
          description: Транспортное средство добавлено

  # === АВТОМОЙКИ И ИНФРАСТРУКТУРА ===
  /автомойки:
    get:
      tags: [Объекты]
      summary: Получение списка автомоек
      operationId: getCarWashes
      responses:
        '200':
          description: Список автомоек
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Автомойка'
    
    post:
      tags: [Объекты]
      summary: Добавление новой автомойки
      operationId: createCarWash
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/НоваяАвтомойка'
      responses:
        '201':
          description: Автомойка создана

  /персонал:
    get:
      tags: [Объекты]
      summary: Получение списка сотрудников
      operationId: getEmployees
      responses:
        '200':
          description: Список сотрудников
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Сотрудник'

  /рабочие-зоны:
    get:
      tags: [Объекты]
      summary: Получение списка рабочих зон
      operationId: getWorkZones
      responses:
        '200':
          description: Список рабочих зон
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/РабочаяЗона'

  /услуги:
    get:
      tags: [Объекты]
      summary: Получение списка доступных услуг
      operationId: getServices
      responses:
        '200':
          description: Список услуг
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Услуга'

  # === ЗАКАЗЫ И БРОНИРОВАНИЯ ===
  /бронирования:
    get:
      tags: [Операции]
      summary: Получение списка бронирований
      operationId: getBookings
      responses:
        '200':
          description: Список бронирований
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Бронирование'
    
    post:
      tags: [Операции]
      summary: Создание нового бронирования
      operationId: createBooking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/НовоеБронирование'
      responses:
        '201':
          description: Бронирование создано

  # === СПРАВОЧНИКИ ===
  /справочники/города:
    get:
      tags: [Справочники]
      summary: Получение списка городов
      operationId: getCities
      responses:
        '200':
          description: Список городов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Город'

  /справочники/районы:
    get:
      tags: [Справочники]
      summary: Получение списка районов
      operationId: getDistricts
      responses:
        '200':
          description: Список районов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Район'

components:
  schemas:
    # Основные сущности
    Клиент:
      type: object
      required: [id, имя, телефон]
      properties:
        id:
          type: integer
          description: Уникальный идентификатор
        имя:
          type: string
          maxLength: 100
        телефон:
          type: string
          pattern: '^\+7\d{10}$'
        email:
          type: string
          format: email
        датаРегистрации:
          type: string
          format: date-time

    НовыйКлиент:
      type: object
      required: [имя, телефон]
      properties:
        имя:
          type: string
          maxLength: 100
        телефон:
          type: string
          pattern: '^\+7\d{10}$'
        email:
          type: string
          format: email

    ОбновлениеКлиента:
      type: object
      properties:
        имя:
          type: string
          maxLength: 100
        телефон:
          type: string
          pattern: '^\+7\d{10}$'
        email:
          type: string
          format: email

    ТранспортноеСредство:
      type: object
      required: [id, модель, регистрационныйНомер, владелецId]
      properties:
        id:
          type: integer
        модель:
          type: string
        регистрационныйНомер:
          type: string
        владелецId:
          type: integer

    НовоеТранспортноеСредство:
      type: object
      required: [модель, регистрационныйНомер, владелецId]
      properties:
        модель:
          type: string
        регистрационныйНомер:
          type: string
        владелецId:
          type: integer

    Автомойка:
      type: object
      required: [id, название, адрес, городId, районId]
      properties:
        id:
          type: integer
        название:
          type: string
        адрес:
          type: string
        городId:
          type: integer
        районId:
          type: integer
        контакты:
          type: string

    НоваяАвтомойка:
      type: object
      required: [название, адрес, городId, районId]
      properties:
        название:
          type: string
        адрес:
          type: string
        городId:
          type: integer
        районId:
          type: integer
        контакты:
          type: string

    Сотрудник:
      type: object
      required: [id, имя, должность, мойкаId]
      properties:
        id:
          type: integer
        имя:
          type: string
        должность:
          type: string
        мойкаId:
          type: integer

    РабочаяЗона:
      type: object
      required: [id, номер, мойкаId]
      properties:
        id:
          type: integer
        номер:
          type: integer
        мойкаId:
          type: integer
        статус:
          type: string
          enum: [свободна, занята, нерабочая]

    Услуга:
      type: object
      required: [id, название, стоимость, мойкаId]
      properties:
        id:
          type: integer
        название:
          type: string
        стоимость:
          type: number
          minimum: 0
        мойкаId:
          type: integer
        длительность:
          type: integer
          description: Длительность в минутах

    Бронирование:
      type: object
      required: [id, датаВремя, статус, клиентId, транспортноеСредствоId, мойкаId, сотрудникId]
      properties:
        id:
          type: integer
        датаВремя:
          type: string
          format: date-time
        статус:
          type: string
          enum: [запланировано, в_процессе, завершено, отменено]
        клиентId:
          type: integer
        транспортноеСредствоId:
          type: integer
        мойкаId:
          type: integer
        сотрудникId:
          type: integer
        рабочаяЗонаId:
          type: integer
        услуги:
          type: array
          items:
            type: integer

    НовоеБронирование:
      type: object
      required: [датаВремя, клиентId, транспортноеСредствоId, мойкаId, сотрудникId]
      properties:
        датаВремя:
          type: string
          format: date-time
        клиентId:
          type: integer
        транспортноеСредствоId:
          type: integer
        мойкаId:
          type: integer
        сотрудникId:
          type: integer
        рабочаяЗонаId:
          type: integer
        услуги:
          type: array
          items:
            type: integer

    Город:
      type: object
      required: [id, название]
      properties:
        id:
          type: integer
        название:
          type: string

    Район:
      type: object
      required: [id, название, городId]
      properties:
        id:
          type: integer
        название:
          type: string
        городId:
          type: integer

  parameters:
    ClientIdPath:
      name: clientId
      in: path
      required: true
      schema:
        type: integer
        minimum: 1
      description: Уникальный идентификатор клиента

  responses:
    NotFound:
      description: Запрашиваемый ресурс не найден
    ValidationError:
      description: Ошибка валидации данных
